name: combine-monitoring-and-reporting-mprns-and-gprns
channels:
  - conda-forge
dependencies:
  - ploomber
  - openpyxl
  - pandas
  - python-dotenv
  - s3fs

  - pip
  - pip:
    - codema-dev-tasks==0.1.0 