# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba  # runs during prebuild
    command: ./bin/micromamba shell init -s bash -p ~/micromamba && alias conda=micromamba && conda activate
