tasks:
  - init: |
      wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest \
        | tar -xvj bin/micromamba \
        &&  ./bin/micromamba shell init -s bash -p ~/micromamba \
        && source ~/.bashrc \
        && alias conda=micromamba \
        && conda activate
