meta:
  extract_upstream: False

tasks:
  - source: download.fetch_s3_file
    name: download_small_areas
    params:
      bucket: codema-dev
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg

  - source: download.check_file_exists
    name: check_urban_atlas_is_uploaded
    params:
      filepath: data/raw/Urban Atlas
    product: data/raw/Urban Atlas

  - source: group_footprints_by_small_areas.py
    name: group_footprints_by_small_areas
    product:
      nb: data/notebooks/group_footprints_by_small_areas.ipynb
      gpkg: data/processed/urban_atlas_in_small_areas.gpkg
      csv: data/processed/urban_atlas_small_area_item_area.csv.gz
    upstream:
      - download_small_areas
      - check_urban_atlas_is_uploaded

