tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg
  - source: codema_dev_tasks.requests.fetch_file
    name: download_cso_networkedgasconsumption2020_html
    params:
      url: https://www.cso.ie/en/releasesandpublications/er/ngc/networkedgasconsumption2020/
    product: data/external/networkedgasconsumption2020.html
  - source: tasks.convert_html_to_tables
    product: data/processed/networkedgasconsumption2020