name: hdd
channels:
  - conda-forge
dependencies:
  # DAG
  - prefect

  # Data Wrangling
  - pandas
  - geopandas

  # Filesystem
  - fsspec
  - openpyxl

  # Dev
  - mypy
  - black
  - isort
  - flake8