name: hdd
channels:
  - conda-forge
  - patrikhlobil 
dependencies:
  # DAG
  - prefect

  # load s3 credentials from .env
  - python-dotenv
  - jupyter

  # Data Wrangling
  - pandas
  - geopandas

  # Filesystem
  - fsspec
  - openpyxl

  # Plotting
  - pandas-bokeh

  # Dev
  - mypy
  - black
  - isort
  - flake8